#!/usr/bin/env python3
"""
Build a PM spot-check worksheet for the vision-verified drawing index.

Every row tells you exactly which PDF to open, which page to turn to, what the
index claims is on that sheet, and which packages inherited the claim. Check the
sheet, tick the box. Rows are ordered by how likely they are to be wrong, so
stopping early still gets you the useful ones.

Usage:  python3 scripts/make-drawing-verification-worksheet.py
Writes: 01-index/drawing-verification-worksheet.md
"""

import json
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "01-index"

# Citations the vision pass actively CHANGED from the pre-vision index. These are
# the highest-value rows: a fabricated pass would get corrections wrong.
CORRECTIONS = {
    "A7-10": "Vision moved ITB-054's overhead coiling door detail here from A4-10 (claimed mislabel).",
    "A11-10": "Vision moved ITB-054's roll-up door head/jamb/sill details here from A4-10 (claimed mislabel).",
    "A4-10": "Vision says the coiling door is NOT here. Confirm absence — this is the other half of the correction.",
    "L1.02": "Vision says this is field-events equipment layout, NOT turf/track notes as previously cited.",
    "L1.03": "Vision says this is track markings + turf install detail + curb detail, NOT high-jump/pole-vault.",
    "L1.07": "Vision says the jump/pole-vault details are here instead.",
}

# Sheets whose content drives a scope decision across several packages.
HIGH_STAKES = {
    "A1-20": "Site Equipment Matrix — treated as the authoritative CFCI responsibility table for 5 packages.",
    "A1-40": "Written spec blocks here substitute for RFP-109's and RFP-094's MISSING spec sections.",
    "A10-30": "Locker Basis-of-Design keynote substitutes for ITB-077's MISSING spec section 10 51 13.",
    "G0-00": "Deferred-submittal list; 'Goal Post Structural Design' left unassigned between ITB-019 and RFP-033.",
}

SAMPLE_HIGH_CONF = 10  # unbiased sample from the 'high' confidence pile
random.seed(20260711)   # stable worksheet across regenerations


def norm(sheet_number: str) -> str:
    """Catalog bookmarks repeat the sheet number for some sheets ('L1.03 L1.03')."""
    parts = sheet_number.split()
    return parts[0] if parts and all(p == parts[0] for p in parts) else sheet_number


def load():
    catalog = {}
    for e in json.loads((INDEX / "drawing-sheet-catalog.json").read_text())["sheets"]:
        catalog[norm(e["sheet_number"])] = e

    vision = {}
    for tag in ("vol1", "vol2", "esdemo"):
        for e in json.loads((INDEX / f"drawing-vision-{tag}.json").read_text())["sheet_assignments"]:
            e["_file_tag"] = tag
            vision[norm(e["sheet_number"])] = e

    pkg_index = json.loads((INDEX / "package-index.json").read_text())
    return catalog, vision, pkg_index


def tier_for(sheet, entry):
    if sheet in CORRECTIONS:
        return 1, CORRECTIONS[sheet]
    if sheet in HIGH_STAKES:
        return 1, HIGH_STAKES[sheet]
    conf = entry.get("confidence")
    if conf == "low":
        return 2, "Agent recorded LOW confidence in this assignment."
    if conf == "medium":
        return 3, "Agent recorded MEDIUM confidence in this assignment."
    return 4, "Random sample from the high-confidence pile."


def main():
    catalog, vision, pkg_index = load()

    rows = []
    high_conf_pool = []
    for sheet, entry in vision.items():
        tier, why = tier_for(sheet, entry)
        if tier == 4:
            high_conf_pool.append((sheet, entry, why))
        else:
            rows.append((tier, sheet, entry, why))

    for sheet, entry, why in random.sample(high_conf_pool, min(SAMPLE_HIGH_CONF, len(high_conf_pool))):
        rows.append((4, sheet, entry, why))

    rows.sort(key=lambda r: (r[0], r[1]))

    tier_names = {
        1: "Tier 1 — Corrections & high-stakes sheets (check these first)",
        2: "Tier 2 — Low-confidence assignments",
        3: "Tier 3 — Medium-confidence assignments",
        4: f"Tier 4 — Random sample of {SAMPLE_HIGH_CONF} high-confidence assignments",
    }

    out = []
    out.append("# Drawing Index — PM Verification Worksheet\n")
    out.append(
        "Generated by `scripts/make-drawing-verification-worksheet.py`. "
        "Each row: open the PDF, turn to the page, compare against the claim, tick the box.\n"
    )
    out.append(
        "> **What this checks.** That the vision pass actually read each sheet and assigned it to the "
        "right packages. A wrong row means some package's Attachment A will be drafted against the wrong "
        "drawing — so this is the gate before Stage 4.\n"
    )
    out.append("**Verdict key** — `OK` claim matches · `WRONG` claim is not on this sheet · "
               "`PARTIAL` claim is right but the sheet has scope the index missed\n")

    current_tier = None
    n = 0
    for tier, sheet, entry, why in rows:
        if tier != current_tier:
            current_tier = tier
            out.append(f"\n---\n\n## {tier_names[tier]}\n")

        cat = catalog.get(sheet)
        if cat:
            pdf = cat["source_file"].split("/")[-1]
            page = cat["page_0idx"] + 1
        else:
            pdf, page = "?? not in catalog", "??"

        pkgs = ", ".join(f"`{p}`" for p in entry.get("package_ids", [])) or "_(none)_"
        n += 1

        out.append(f"### {n}. Sheet `{sheet}` — {entry.get('sheet_title','')}\n")
        out.append(f"- **Open:** `{pdf}` → **page {page}**")
        out.append(f"- **Why this row:** {why}")
        out.append(f"- **Assigned to:** {pkgs}")
        out.append(f"- **Index claims:** {entry.get('rationale','').strip()}")
        out.append("")
        out.append("| Verdict | Notes |")
        out.append("|---|---|")
        out.append("| ☐ OK ☐ WRONG ☐ PARTIAL | |")
        out.append("")

    out.append("\n---\n")
    out.append("## When you're done\n")
    out.append(
        "- Any **WRONG** row → tell me the sheet and I'll re-read it and repair the affected packages.\n"
        "- Several **PARTIAL** rows → that's the known under-assignment pattern (see below); worth a "
        "targeted second pass over the affected sheets rather than a full re-run.\n"
        "- All **OK** → the index is good to carry into Stage 4 drafting.\n"
    )
    out.append(
        "## Known weakness this worksheet is looking for\n\n"
        "Two independent spot-checks (A7-10, A10-30) found the recorded rationales **verbatim accurate** "
        "but **under-inclusive** — the agent captured each sheet's headline scope and skipped secondary "
        "trades visible on the same sheet:\n\n"
        "- **A7-10** was assigned `ITB-054`/`RFP-031`, but the sheet also shows a stainless steel work "
        "table and tray slide (`ITB-085`), 2x wood framing / PT plywood / continuous nailer (`RFP-060`), "
        "and sealant (`ITB-040`).\n"
        "- **A10-30** was assigned `ITB-071`/`ITB-077`, but its Finish Legend calls out FRP-1/FRP-2 fiber "
        "reinforced plastic panels and PT-2 accent paint (`RFP-060`, whose title explicitly includes FRP), "
        "plus keynote 9-03 wall base (possibly `ITB-066`, which has no spec section at all).\n\n"
        "So the failure mode is **missed scope, not invented scope** — which is the safer direction, but "
        "it means a package can silently lose a drawing it should have inherited. Bias your checking "
        "toward *what else is on the sheet* rather than *is the stated claim true*.\n"
    )

    dest = INDEX / "drawing-verification-worksheet.md"
    dest.write_text("\n".join(out))
    print(f"wrote {dest.relative_to(ROOT)} — {n} rows")


if __name__ == "__main__":
    main()
